### ISSUE TITLE
fetch_node_details_default.a is not a constructor

### ISSUE THREAD

**Issue by iamgenchi** [torusresearch/fetch-node-details#23]
Implementing [torus-web-sdk](https://github.com/torusresearch/torus-direct-web-sdk) throws an issue that seems related to this package.

```
fetch_node_details_default.a is not a constructor
```

![image](https://user-images.githubusercontent.com/81058044/117884114-9617c480-b2ef-11eb-9807-0fc132622aa6.png)

```
"dependencies": {
  "@toruslabs/torus-direct-web-sdk": "^4.13.1",
  "next": "10.2.0",
  "react": "17.0.2",
  "react-dom": "17.0.2"
},
```

Implementation is the same as the example for React.

```
  componentDidMount = async () => {
    try {
      const torusdirectsdk = new TorusSdk({
        baseUrl: `${window.location.origin}/serviceworker`,
        enableLogging: true,
        network: "testnet", // details for test net
      });

      await torusdirectsdk.init({ skipSw: false });

      this.setState({ torusdirectsdk: torusdirectsdk });
    } catch (error) {
      console.error(error, "mounted caught");
    }
  };
```

**Comment by chaitanyapotti** [comment]
v2.5.0 is bundled using webpack 5 and it causes compatibility issues.
v2.6.0 is bundled using webpack 4 now.

**Comment by iamgenchi** [comment]
@chaitanyapotti The last version of NextJS (10.2.0) is now using webpack 5 by default, this would mean users have to downgrade to Webpack 4. 

Do you need assistance to provide compatibility with Webpack 5?

**Comment by chaitanyapotti** [comment]
packages bundled with webpack 4 work perfectly fine with webpack 5 projects. (which is the case with the latest release)
packages bundled with webpack 5 won't work with webpack 4 projects.

Hence, this package is being bundled with webpack 4 now.
Please update to the latest sdk version
