### ISSUE TITLE
NPM warnings while trying to install lib using NPM v7 

### ISSUE THREAD

**Issue by christophercr** [torusresearch/fetch-node-details#31]
Same issue as in https://github.com/torusresearch/torus-embed/issues/370:

**Describe the bug**
While installing this library using NPM 7, shows the following warnings due to a [requirement of NPM 6 defined in the `package.json`](https://github.com/torusresearch/fetch-node-details/blob/4d370c303f94f122339d84fd2e84e9251f3f28ab/package.json#L102).

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@toruslabs/fetch-node-details@2.7.1',
npm WARN EBADENGINE   required: { node: '>=14.17.0', npm: '~6.x' },
npm WARN EBADENGINE   current: { node: 'v14.17.4', npm: '7.20.3' }
npm WARN EBADENGINE }
```

**To Reproduce**
1. Make sure you have NPM 7 installed
2. include the dependency in your `package.json`: `"@toruslabs/fetch-node-details": "^2.7.1",`
3. Run `npm install`
4. Installation shows several warnings (mentioned above)

**Expected behavior**
Installation should be smooth without warnings related to latest versions of NPM.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 1.x.x

**Additional context**
For example, this is the line in `package.json` of one of the affected packages where the restriction is set: https://github.com/torusresearch/fetch-node-details/blob/4d370c303f94f122339d84fd2e84e9251f3f28ab/package.json#L102

This file should be adapted in the different `@toruslabs` packages to also allow NPM v7 (which is backwards compatible).

**Comment by chaitanyapotti** [comment]
Fixed in 3.1.0
