### ISSUE TITLE
Testnet is hardcoded to `ropsten` network

### ISSUE THREAD

**Issue by kylemantesso** [torusresearch/fetch-node-details#46]
Need to make the network map dynamic so we can use other chain / network combos

```
export const NETWORK_MAP = {
  [TORUS_NETWORK.MAINNET]: "mainnet",
  [TORUS_NETWORK.TESTNET]: "ropsten",
  [TORUS_NETWORK.CYAN]: "polygon-mainnet",
  [TORUS_NETWORK.AQUA]: "polygon-mainnet",
};
```

**Comment by chaitanyapotti** [comment]
This is not related to customer network contracts.
This only reads the details of Torus Network nodes from smart contracts present on the respective networks
